#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 29 11:20:07 2018

@author: lijixuan
"""

# Problem 1 - Paying Debt off in a Year

#Write a program to calculate the credit card balance after one year if a person only pays the minimum monthly payment required by the credit card company each month.

#The following variables contain values as described below:

#balance - the outstanding balance on the credit card

#annualInterestRate - annual interest rate as a decimal

#monthlyPaymentRate - minimum monthly payment rate as a decimal

#For each month, calculate statements on the monthly payment and remaining balance. At the end of 12 months, print out the remaining balance. Be sure to print out no more than two decimal digits of accuracy

# =============================================================================
# A summary of the required math is found below:
# 
# Monthly interest rate= (Annual interest rate) / 12.0
# Minimum monthly payment = (Minimum monthly payment rate) x (Previous balance)
# Monthly unpaid balance = (Previous balance) - (Minimum monthly payment)
# Updated balance each month = (Monthly unpaid balance) + (Monthly interest rate x Monthly unpaid balance)
# 
# =============================================================================

month = 0
totalPay = 0
#balance = 42
#annualInterestRate = 0.2
#monthlyPaymentRate = 0.04

while month < 12:
    monthlyInterestRate = annualInterestRate/12
    minPay = monthlyPaymentRate * balance
    unpayBal = balance - minPay
    totalPay += minPay
    balance = unpayBal + (monthlyInterestRate * unpayBal)
    month += 1
#    print('Month: ' + str(month))
#    print('Minimum monthly payment: ' + str(round(minPay,2)))
#    print('Remaining balance: ' + str(round(balance,2)))
# print('Total paid: ' + str(round(totalPay,2)))
print(' Remaining balance: ' + str(round(balance,2)))

# =============================================================================
# test case:
# # Test Case 1:
# 	      balance = 42
# 	      annualInterestRate = 0.2
# 	      monthlyPaymentRate = 0.04
# 	      
# 	      # Result Your Code Should Generate Below:
# 	      Remaining balance: 31.38
#                     
#           # To make sure you are doing calculation correctly, this is the 
#           # remaining balance you should be getting at each month for this example
#             Month 1 Remaining balance: 40.99
#             Month 2 Remaining balance: 40.01
#             Month 3 Remaining balance: 39.05
#             Month 4 Remaining balance: 38.11
#             Month 5 Remaining balance: 37.2
#             Month 6 Remaining balance: 36.3
#             Month 7 Remaining balance: 35.43
#             Month 8 Remaining balance: 34.58
#             Month 9 Remaining balance: 33.75
#             Month 10 Remaining balance: 32.94
#             Month 11 Remaining balance: 32.15
#             Month 12 Remaining balance: 31.38
# =============================================================================

#Problem 2 - Paying Debt Off in a Year

#Now write a program that calculates the minimum fixed monthly payment needed in order pay off a credit card balance within 12 months. By a fixed monthly payment, we mean a single number which does not change each month, but instead is a constant amount that will be paid each month.

#In this problem, we will not be dealing with a minimum monthly payment rate.

#The following variables contain values as described below:

#balance - the outstanding balance on the credit card

#annualInterestRate - annual interest rate as a decimal

#Assume that the interest is compounded monthly according to the balance at the end of the month (after the payment for that month is made). The monthly payment must be a multiple of $10 and is the same for all months. Notice that it is possible for the balance to become negative using this payment scheme, which is okay. A summary of the required math is found below:

# =============================================================================
# 
# #Monthly interest rate = (Annual interest rate) / 12.0
# #Monthly unpaid balance = (Previous balance) - (Minimum fixed monthly payment)
# #Updated balance each month = (Monthly unpaid balance) + (Monthly interest rate x Monthly unpaid balance)
# 
# =============================================================================

monthlyPaymentRate = 0
init_balance = balance
monthlyInterestRate = annualInterestRate/12

while balance > 0:
    for i in range(12):
        balance = balance - monthlyPaymentRate + ((balance - monthlyPaymentRate) * monthlyInterestRate)
    if balance > 0:
        monthlyPaymentRate += 10
        balance = init_balance
    elif balance <= 0:
        break
print('Lowest Payment:', monthlyPaymentRate)

# =============================================================================
# Problem 3 - Using Bisection Search to Make the Program Faster
# =============================================================================

init_balance = balance
monthlyInterestRate = annualInterestRate/12
lower = init_balance/12
upper = (init_balance * (1 + monthlyInterestRate)**12)/12.0
epsilon = 0.03

while abs(balance) > epsilon:
    monthlyPaymentRate = (upper + lower)/2
    balance = init_balance
    for i in range(12):
        balance = balance - monthlyPaymentRate + ((balance - monthlyPaymentRate) * monthlyInterestRate)
    if balance > epsilon:
        lower = monthlyPaymentRate
    elif balance < -epsilon:
        upper = monthlyPaymentRate
    else:
        break
print('Lowest Payment:', round(monthlyPaymentRate, 2))